#!/bin/bash

if [ -p /dev/stdin ]; then
	text=`cat -`
	csv=${1}
else
	if [[ "${1}" == "" ]] && [[ "${2}" == "" ]]; then
		echo "Usage:"
		echo "  - hcat [FILE] [KEYWORD_OF_CSV]"
		echo "  - [STRING] | hcat [KEYWORD_OF_CSV]"
		exit
	else
		text=`cat ${1}`
		csv=${2}
	fi
fi

if [ ! -z "${csv}" ]; then
	pattern=`echo $csv | tr -s ',' '|'`

	htext=`echo -e "${text}" | perl -pe "s/(${pattern})/\e[1;33m$&\e[0m/g"`
else
	htext=$text
fi

echo -e "${htext}"

